// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package authStore

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	UserID     string         `json:"user_id"`
	Token      sql.NullString `json:"token"`
	TimeIssued sql.NullTime   `json:"time_issued"`
	ExpireAt   time.Time      `json:"expire_at"`
	Deleted    sql.NullTime   `json:"deleted"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type User struct {
	UserID     string       `json:"user_id"`
	Name       string       `json:"name"`
	Email      string       `json:"email"`
	ProfilePic string       `json:"profile_pic"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
	CreatedAt  sql.NullTime `json:"created_at"`
}
