// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package authStore

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, userID string) (User, error)
}

var _ Querier = (*Queries)(nil)
