// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package playlistStore

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Playlist struct {
	PlaylistID   string                `json:"playlist_id"`
	UserID       string                `json:"user_id"`
	Title        string                `json:"title"`
	Url          string                `json:"url"`
	ThumbnailUrl string                `json:"thumbnail_url"`
	Channel      string                `json:"channel"`
	Videos       pqtype.NullRawMessage `json:"videos"`
	UpdatedAt    sql.NullTime          `json:"updated_at"`
	CreatedAt    sql.NullTime          `json:"created_at"`
}
