// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package playlistStore

import (
	"context"
)

type Querier interface {
	AddNewPlaylist(ctx context.Context, arg AddNewPlaylistParams) error
	DeletePlaylistForUser(ctx context.Context, arg DeletePlaylistForUserParams) error
	GetAllUserPlaylists(ctx context.Context, userID string) ([]Playlist, error)
	GetPlaylistById(ctx context.Context, playlistID string) (Playlist, error)
	GetPlaylistForUser(ctx context.Context, arg GetPlaylistForUserParams) (Playlist, error)
	UpdatePlaylistForUser(ctx context.Context, arg UpdatePlaylistForUserParams) error
}

var _ Querier = (*Queries)(nil)
